relationships = [
    'about to hit', 'approaching', 'balancing on', 'biting', 'blowing out', 
    'boarding', 'carrying', 'catching', 'chasing', 'chewing', 'cleaning', 
    'climbing', 'coming down', 'coming from', 'coming out of', 'cooked in', 
    'covering', 'crossing', 'cutting', 'dragging', 'drinking', 'drinking from', 
    'driving', 'driving down', 'driving on', 'eating', 'eating from', 
    'eating in', 'entering', 'exiting', 'falling off', 'feeding', 'flying', 
    'flying above', 'flying in', 'flying over', 'flying through', 
    'followed by', 'following', 'getting on', 'going down', 'going into', 
    'going through', 'grabbing', 'grazing in', 'grazing on', 'guiding', 
    'helping', 'herding', 'hitting', 'holding', 'holding onto', 'hugging', 
    'jumping in', 'jumping off', 'jumping on', 'jumping over', 'kicking', 
    'leading', 'leaving', 'licking', 'looking at', 'looking down at', 
    'looking for', 'looking in', 'looking into', 'looking out', 
    'looking through', 'making', 'moving', 'observing', 'opening', 
    'passing', 'petting', 'picking up', 'playing', 'playing in', 
    'playing on', 'playing with', 'pointing at', 'pointing to', 'posing with', 
    'pouring', 'preparing', 'pulled by', 'pulling', 'pushed by', 'pushing', 
    'reaching for', 'reading', 'riding', 'riding in', 'riding on', 
    'running across', 'running in', 'running on', 'running through', 
    'same color', 'same material', 'selling', 'serving', 'skating on', 
    'skiing in', 'skiing on', 'smelling', 'smiling at', 'sniffing', 
    'staring at', 'swimming in', 'swinging', 'talking on', 'talking to', 
    'throwing', 'tossing', 'traveling down', 'traveling on', 'trying to catch', 
    'tying', 'typing on', 'using', 'wading in', 'waiting for', 'walking across', 
    'walking along', 'walking behind', 'walking by', 'walking down', 
    'walking in', 'walking into', 'walking near', 'walking next to', 
    'walking on', 'walking past', 'walking through', 'walking to', 
    'walking toward', 'walking towards', 'walking with', 'washing', 
    'watching', 'wearing', 'working in', 'working on', 'full of', 'of',
    'with', 'same shape'
]

spatial_relationships = [
    'above', 'along', 'around', 'at', 'attached to', 'behind', 'below', 
    'beneath', 'beside', 'between', 'bigger than', 'by', 'chained to', 
    'close to', 'connected to', 'contain', 'covered by', 'covered in', 
    'covered with', 'decorated with', 'displayed on', 'draped over', 
    'drawn on', 'enclosing', 'facing', 'filled with', 'floating in', 
    'floating on', 'growing along', 'growing behind', 'growing in', 
    'growing next to', 'growing on', 'hang from', 'hanging above', 
    'hanging from', 'hanging in', 'hanging off', 'hanging on', 
    'hanging out of', 'hanging over', 'hidden by', 'higher than', 'hung on', 
    'in', 'in between', 'in front of', 'in the middle of', 'inside', 
    'kept in', 'larger than', 'leaning against', 'leaning on', 'leaning over', 
    'longer than', 'lying in', 'lying inside', 'lying next to', 'lying on', 
    'lying on top of', 'mixed with', 'mounted on', 'mounted to', 'near', 
    'next to', 'on', 'on the back of', 'on the bottom of', 
    'on the edge of', 'on the front of', 'on the other side of', 
    'on the side of', 'on top of', 'over', 'painted on', 'parked along', 
    'parked at', 'parked behind', 'parked beside', 'parked by', 
    'parked in', 'parked in front of', 'parked near', 'parked next to', 
    'parked on', 'perched on', 'piled on', 'plugged into', 'printed on', 
    'reflected in', 'reflected on', 'reflecting in', 'resting on', 
    'scattered on', 'seen through', 'sitting around', 
    'sitting at', 'sitting behind', 'sitting beside', 'sitting by', 
    'sitting in', 'sitting in front of', 'sitting near', 'sitting next to', 
    'sitting on', 'sitting on top of', 'sitting under', 'sitting with', 
    'sleeping on', 'sprinkled on', 'stacked on', 'standing against', 
    'standing around', 'standing at', 'standing behind', 'standing beside', 
    'standing by', 'standing in', 'standing in front of', 'standing near', 
    'standing next to', 'standing on', 'standing on top of', 'standing under', 
    'stuck in', 'stuck on', 'surrounded by', 'surrounding', 'taller than', 
    'tied to', 'to the left of', 'to the right of', 'topped with', 'touching', 
    'under', 'underneath', 'worn on', 'wrapped around', 'wrapped in'
]